language: ruby
rvm:
  - 2.1.5
cache: bundler
bundler_args: --without production --deployment
addons:
  postgresql: "9.3"
before_install:
  - gem install bundler --pre
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rspec
#debug
#script: "RAILS_ENV=test bundle exec rake test:ci --trace"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/047149ce1ecf8d572a02
    on_success: change
    on_failure: always
    on_start: false     # default: false

